Release 4.1.0
Sunbird-Ed/SunbirdEd-mobile-app pull request #2394
Opened 2021-07-09 12:19 UTC by sujithsojan

2021-07-09 12:33 UTC, subranil requested changes

2021-07-09 12:33 UTC, subranil commented on src/app/download-manager/download-manager.page.ts
>        })
Put semicolon at the end

2021-07-09 12:33 UTC, subranil commented on src/app/enrolled-course-details-page/enrolled-course-details-page.ts
> -      .catch((error) => {
same as before put semicolon afte then clock closure

2021-07-09 12:33 UTC, subranil commented on src/app/enrolled-course-details-page/enrolled-course-details-page.ts
> -            .catch((error) => {
put semicolon

2021-07-09 12:33 UTC, subranil commented on src/app/enrolled-course-details-page/enrolled-course-details-page.ts
> -      }).catch(() => {
put semicolon

2021-07-09 12:33 UTC, subranil commented on src/app/manage-learn/domain-ecm-listing/domain-ecm-lsiting/domain-ecm-lsiting.component.ts
>            })
put semicolon at the end of then block

2021-07-09 12:33 UTC, subranil commented on src/app/manage-learn/ecm-listing/ecm-listing.page.ts
>            })
put semicolon at the end of then block

2021-07-09 12:33 UTC, subranil commented on src/app/manage-learn/image-listing/image-listing/image-listing.component.ts
>        })
put semicolon at the end of then block

2021-07-09 12:33 UTC, subranil commented on src/app/manage-learn/image-listing/image-listing/image-listing.component.ts
>          })
put semicolon at the end of then block

2021-07-09 12:33 UTC, subranil commented on src/app/manage-learn/image-listing/image-listing/image-listing.component.ts
>          })
put semicolon at the end of then block

2021-07-09 12:33 UTC, subranil commented on src/app/manage-learn/observation/observation-detail/observation-detail.component.ts
>          })
put semicolon at the end of then block

2021-07-09 12:33 UTC, subranil commented on src/app/manage-learn/observation/observation-detail/observation-detail.component.ts
> -          console.log(error);
put semicolon at the end of then block

2021-07-09 12:54 UTC, subranil approved these changes

2021-07-14 07:41 UTC, subranil approved these changes

2021-07-14 08:25 UTC, swayangjit approved these changes

2021-07-14 08:25 UTC, merged